include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_relative_imports
    - use_super_parameters
    - only_throw_errors
    - directives_ordering
    - prefer_single_quotes
    - avoid_escaping_inner_quotes
